<a href="https://colab.research.google.com/github/jeeswan/ML-From-Scratch/blob/main/Introduction%20to%20Numpy/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Introduction to Numpy
What will we cover?
- Creating arrays
- Multi dimensional array
- Randomly gnerated array
- Element wise operation
      - Comparision wise operaton
      - Logical operation
- Summarizing operation


### ✅Single Dimensional array

In [1]:
import numpy as np

In [4]:
var = np.zeros(5)

In [5]:
print(type(var))

<class 'numpy.ndarray'>


In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [9]:
np.full(10, 3)

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [11]:
a = np.array([1, 2, 3, 4])

In [12]:
a[2] = 5

In [13]:
a

array([1, 2, 5, 4])

In [14]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

Create array with evenly spaced numbers within a specified range

In [15]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

### ✅Multi Dimensional array

In [16]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

Create a multi dimensional unit array of size (5, 2)

In [18]:
np.ones((5, 2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

Generate a random array of size (3, 5) with elements of your choice

In [42]:
a = np.array([
    [1, 2, 3, 4, 5],
    [2, 3, 4, 5, 1],
    [3, 4, 5, 1, 2]
      ])

In [43]:
a

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 1],
       [3, 4, 5, 1, 2]])

In [45]:
a[2] = 1
a

array([[1, 2, 3, 4, 5],
       [2, 3, 4, 5, 1],
       [1, 1, 1, 1, 1]])

In [46]:
a[0, 1] = 9
a

array([[1, 9, 3, 4, 5],
       [2, 3, 4, 5, 1],
       [1, 1, 1, 1, 1]])

In [47]:
a[:, 2] = 2

In [48]:
a

array([[1, 9, 2, 4, 5],
       [2, 3, 2, 5, 1],
       [1, 1, 2, 1, 1]])

### ✅Randomly generated arrays

- Numpy can create array filled with random numbers
- To ensure the reproducibility, you can set a seed using np.random.seed()
- Everytime you run the code with np.random.seed(2), it will generate the exact same random numbers, if you change the seed values the sequences of random numbers will be changed

In [52]:
np.random.rand(3)

array([0.30789587, 0.75367401, 0.80271608])

In [56]:
np.random.seed(2)
np.random.rand(3)

array([0.4359949 , 0.02592623, 0.54966248])

In [58]:
np.random.seed(5)
np.random.rand(5, 2)

array([[0.22199317, 0.87073231],
       [0.20671916, 0.91861091],
       [0.48841119, 0.61174386],
       [0.76590786, 0.51841799],
       [0.2968005 , 0.18772123]])

In [59]:
np.random.randn(5, 2)

array([[ 0.18760323, -0.32986996],
       [-1.19276461, -0.20487651],
       [-0.35882895,  0.6034716 ],
       [-1.66478853, -0.70017904],
       [ 1.15139101,  1.85733101]])

In [60]:
np.random.seed(42)
np.random.randint(low=0, high=100, size=(5, 2))

array([[51, 92],
       [14, 71],
       [60, 20],
       [82, 86],
       [74, 74]])

### ✅Element wise operation

In [62]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

comparision operation
- perform element wise comparision andn create boolean arrays

In [63]:
a

array([0, 1, 2, 3, 4])

In [65]:
b = (10 + (a*2))
b

array([10, 12, 14, 16, 18])

In [64]:
a >= 2

array([False, False,  True,  True,  True])

In [66]:
a > b

array([False, False, False, False, False])

Summarizing
- Numpy provides functions for summarixing array of data

In [67]:
b

array([10, 12, 14, 16, 18])

In [69]:
#Standard Deviation
a.std()

1.4142135623730951

In [70]:
# min value of an array
a.min()

0

In [72]:
# max value of an array
a.max()

4

In [73]:
# sum of an array
a.sum()

10